include:
  - board: nice_nano_v2
    shield: ferris_sweep_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: ferris_sweep_right
  - board: nice_nano_v2
    shield: settings_reset

